# Generated by Django 5.0.1 on 2024-01-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('orderNumber', models.UUIDField()),
                ('customerId', models.IntegerField()),
                ('articles', models.JSONField()),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
