# Generated by Django 5.0.1 on 2024-02-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name_plural': 'Orders'},
        ),
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('open', 'Offen'), ('in progress', 'In Bearbeitung'), ('shipped', 'Versendet'), ('delivered', 'Zugestellt')], default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='orders',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
