# Generated by Django 5.0.1 on 2024-01-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('brandName', models.CharField(max_length=50)),
                ('modelName', models.CharField(max_length=50)),
                ('modelYear', models.IntegerField()),
                ('initalRegistration', models.DateField()),
                ('licensePlate', models.CharField(max_length=10)),
            ],
        ),
    ]
