# Generated by Django 5.0.1 on 2024-02-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('free', 'Frei'), ('on tour', 'Auf Tour'), ('garage', 'Werkstatt')], default='free', max_length=20),
        ),
    ]
