# Generated by Django 5.0.1 on 2024-02-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicle_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('free', 'Frei'), ('on tour', 'Auf Tour'), ('garage', 'Werkstatt')], default='garage', max_length=20),
        ),
    ]
